### ISSUE TITLE
Basic histogram attempt throws TypeError

### ISSUE THREAD

**Issue by j-s-ashley** [j-s-ashley/DisplacedTauAnalysis#1]
Awkward and NumPy aren't playing nicely together in [dtt-hist.py](https://github.com/j-s-ashley/DisplacedTauAnalysis/blob/7d6398b775ff5f77052dccefc14c6bf35bd35641/dtt-hist.py)

<details>
<summary>Error message</summary>
/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/coffea/nanoevents/schemas/fcc.py:5: FutureWarning: In version 2025.1.0 (target date: 2024-12-31 11:59:59-06:00), this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="coffea.*")
after the first `import coffea` or use `@pytest.mark.filterwarnings("error:::coffea.*")` in pytest.
Issue: coffea.nanoevents.methods.vector will be removed and replaced with scikit-hep vector. Nanoevents schemas internal to coffea will be migrated. Otherwise please consider using that package!.
  from coffea.nanoevents.methods import vector
Traceback (most recent call last):
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/_dispatch.py", line 64, in dispatch
    next(gen_or_result)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/operations/ak_to_numpy.py", line 48, in to_numpy
    return _impl(array, allow_missing)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/operations/ak_to_numpy.py", line 58, in _impl
    numpy_layout = layout.to_backend(backend)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/contents/content.py", line 1207, in to_backend
    return self._to_backend(backend)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/contents/numpyarray.py", line 1367, in _to_backend
    self._raw(backend.nplike),
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/contents/numpyarray.py", line 189, in _raw
    return to_nplike(self.data, nplike, from_nplike=self._backend.nplike)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/_nplikes/__init__.py", line 31, in to_nplike
    raise TypeError(
TypeError: Converting from an nplike without known data to an nplike with known data is not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/eos/home-j/jashley/bubbles/gamma/DisplacedTauAnalysis/dtt-hist.py", line 52, in <module>
    plt.hist(flattened_scores, bins=bins, histtype='step', label='Truth Distribution')
  File "/usr/lib64/python3.9/site-packages/matplotlib/pyplot.py", line 2853, in hist
    return gca().hist(
  File "/usr/lib64/python3.9/site-packages/matplotlib/__init__.py", line 1364, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/lib64/python3.9/site-packages/matplotlib/axes/_axes.py", line 6672, in hist
    x = cbook._reshape_2D(x, 'x')
  File "/usr/lib64/python3.9/site-packages/matplotlib/cbook/__init__.py", line 1395, in _reshape_2D
    X = X.to_numpy()
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/dask_awkward/lib/core.py", line 1606, in wrapper
    return self.map_partitions(
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/dask_awkward/lib/core.py", line 1667, in map_partitions
    return map_partitions(func, self, *args, traverse=traverse, **kwargs)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/dask_awkward/lib/core.py", line 2186, in map_partitions
    return _map_partitions(
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/dask_awkward/lib/core.py", line 2022, in _map_partitions
    meta = map_meta(fn, *args, **kwargs)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/dask_awkward/lib/core.py", line 2538, in map_meta
    meta = fn(*to_meta(deps))
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/dask_awkward/lib/core.py", line 1982, in __call__
    return self.fn(*args, **kwargs)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/dask_awkward/lib/core.py", line 2638, in __call__
    return getattr(coll, self.attr)(*args, **self.kwargs)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/highlevel.py", line 506, in to_numpy
    return ak.operations.to_numpy(self, allow_missing=allow_missing)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/_dispatch.py", line 72, in dispatch
    return gen_or_result
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/_errors.py", line 85, in __exit__
    self.handle_exception(exception_type, exception_value)
  File "/afs/cern.ch/user/j/jashley/.local/lib/python3.9/site-packages/awkward/_errors.py", line 95, in handle_exception
    raise self.decorate_exception(cls, exception)
TypeError: Converting from an nplike without known data to an nplike with known data is not supported

This error occurred while calling

    ak.to_numpy(
        <Array-typetracer [...] type='## * float32'>
        allow_missing = True
    )
</details>

**Comment by dally96** [comment]
Since you have delayed = True, all of your arrays are dask arrays. This won't plot in matplotlib, so you have to add a .compute() to the end of the array you're trying to plot.

**Comment by j-s-ashley** [comment]
> Since you have delayed = True, all of your arrays are dask arrays. This won't plot in matplotlib, so you have to add a .compute() to the end of the array you're trying to plot.

Resolved with this solution. Thanks!
